### ISSUE TITLE
Leaving oot in the pause screen causes heavy flashing

### ISSUE THREAD

**Issue by MintyJelly** [GhostlyDark/EMG#5] opened 2023-01-11 21:09 UTC
The screen appears dimmer with heavy rapid flashing. I can also see a faint text in the background which I believe spells kokiri forest. This may be related to my post about gsync as turning off gsync has fixed the issue currently.

**Comment by GhostlyDark** [comment] 2023-01-12 06:12
Duplicate of #3

**Closed by GhostlyDark** 2023-01-12 06:12 UTC
