### ISSUE TITLE
Issues with full screen switch.

### ISSUE THREAD

**Issue by MintyJelly** [GhostlyDark/EMG#2] opened 2023-01-11 19:45 UTC
The emulator will crash when pressing the full screen button three times while the windowed resolution is set to 2240x1680 or higher. Full screen at start must be enabled or pressing the full screen button will not crash but it will also not allow the emulator to enter full screen.

As a side note, when the windowed resolution is set to 2560x1920, the screen is not properly fitted in full screen. Pressing the full screen button two times will properly scale the display.

**Comment by GhostlyDark** [comment] 2023-01-12 06:13
I assume you are using GLideN64 with EMG v0.9.3?

**Comment by MintyJelly** [comment] 2023-01-12 07:06
Yes to both.

**Comment by GhostlyDark** [comment] 2023-01-12 16:49
I did push a new release that fixes some error messages and warnings when going into fullscreen and resizing the window. I don't expect it to fix the issue however. I am personally unable to reproduce any crashing when going in and out of fullscreen, no matter the resolution.

Fullscreen is really funky using mupen CLI though. Unsure what to blame here.
https://github.com/gonetz/GLideN64/issues/2736

**Comment by GhostlyDark** [comment] 2023-03-01 21:03
Closing this as semi-completed. Further issues should be reported in the mupen64plus-console-ui repo, since the command line interface is the source for the weird fullscreen behaviour.

**Closed by GhostlyDark** 2023-03-01 21:03 UTC
